package(
    default_visibility = ['//:__subpackages__'],
)

cc_library(
    name = 'exception',
    hdrs = ['exception.h'],
    strip_include_prefix = '//src',
    deps = [
        '@com_github_neargye_magic_enum//:magic_enum',
    ],
)
