package(
    default_visibility = ['//:__subpackages__'],
)

cc_library(
    name = 'logging',
    srcs = ['logging.cpp'],
    hdrs = ['logging.h'],
    deps = [
        '@com_google_absl//absl/log',
        '@com_google_absl//absl/strings',
    ],
)
