package(
    default_visibility = ['//:__subpackages__'],
)

cc_library(
    name = 'log_sink',
    srcs = ['log_sink.cpp'],
    hdrs = ['log_sink.h'],
    deps = [
        '@com_google_absl//absl/log',
        '@com_google_absl//absl/strings',
        '@com_google_absl//absl/time',
    ],
)
