package(
    default_visibility = ["//:__subpackages__"],
)

cc_library(
    name = "processor",
    srcs = [
        "plus.cpp",
        "unsupported_command.cpp",
    ],
    hdrs = [
        "plus.h",
        "unsupported_command.h",
    ],
    deps = [
        "@com_github_baidu_babylon//:anyflow",
    ],
)
