package(
    default_visibility = ['//:__subpackages__'],
)

cc_library(
    name = 'netimpl',
    # srcs = glob(['*.cpp'])
    srcs = ['netimpl.cpp'],
    hdrs = ['netimpl.h'],
    deps = [
    ],
)

