name: ielts-ai ci
on:
  push:
    branches:
      - main

jobs:
  my-job:
    name: generate output
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: test gcc
      run: |
        echo $(gcc -v)
  
    - name: generate
      run: |
        bazel build //...
        mkdir -p output/bin
        mv ./bazel-bin/src/ielts_ai output/bin/

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        since_last_remote_commit: true
        separator: ","
  
    - name: deploy
      uses: appleboy/scp-action@v0.1.7
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: ${{ steps.changed-files.outputs.all_changed_files }}
        target: /home/work/ielts-ai/

