name: ielts-ai ci
on:
  push:
    branches:
      - main

jobs:
  my-job:
    name: generate output
    runs-on: ubuntu-latest
    container: docker.io/centos:8
    steps:
    - uses: actions/checkout@v2
    - name: install env
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $(gcc -v)
        sudo yum install -y bazel
    - name: bazel build
      run: |
        bazel build //...
