on:
  push:
    tags:
      - 'v*'

name: ielts-ai ci

jobs:
  my-job:
    name: Generate Artifact
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
  
    - name: Print env
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}
    
    - name: Build
      run: |
        bazel build //...
        mkdir -p output/bin output/conf
        mv ./bazel-bin/src/ielts_ai output/bin/
        mv ./conf/* output/conf/
        zip --junk-paths output output/*
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: release_artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output.zip
        asset_name: output.zip
        asset_content_type: application/zip
  
    - name: copy file to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: ${{ steps.release_artifacts.outputs.browser_download_url }}
        target: ${{ secrets.DEPLOY_PATH }}

    - name: Restart
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          ll -al

