on:
  push:
    tags:
      - 'v*'

name: ielts-ai ci

jobs:
  my-job:
    name: Generate Artifact
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
  
    - name: Print env
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}
    
    - name: Build
      run: |
        bazel build //...
        mkdir -p output/bin output/conf
        mv ./bazel-bin/src/ielts_ai output/bin/
        mv ./conf/* output/conf/
        zip -r output output/*

    - name: Release
      id: release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          output.zip

    # - name: Upload
    #   id: upload
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: output
    #     path: output.zip

    # - name: Upload Release Asset
    #   id: release_artifacts
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     # upload_url: ${{ github.event.release.upload_url }}
    #     upload_url: ${{ steps.upload.outputs.output }}
    #     asset_path: ./output.zip
    #     asset_name: output.zip
    #     asset_content_type: application/zip
  
    # - name: copy file to server
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     password: ${{ secrets.SERVER_PASSWORD }}
    #     port: ${{ secrets.SERVER_PORT }}
    #     source: "output.zip"
    #     # source: ${{ steps.release_artifacts.outputs.browser_download_url }}
    #     target: ${{ secrets.DEPLOY_PATH }}
  
    - name: Deploy & Restart
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          wget ${{ steps.release.outputs.url }}
          unzip output.zip
          ll -al output/

