on:
  push:
    tags:
      - 'v*'

name: ielts-ai ci

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Build
      run: |
        bazel build //...
        mkdir -p output/bin output/conf
        mv ./bazel-bin/src/ielts_ai output/bin/
        mv ./conf/* output/conf/
        sed -i "s/TOKEN_WX_MINIPROGRAM/${{ secrets.TOKEN_WX_MINIPROGRAM }}/g" output/conf/auth.yaml

    - name: Backup old version
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          mv ${{ secrets.DEPLOY_PATH }} ${{ secrets.DEPLOY_PATH }}.$(date +%Y%m%d_%H%M)

    - name: Deploy
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: ./output/*
        target: ${{ secrets.DEPLOY_PATH }}
        strip_components: 1
  
  restart:
    name: Restart
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          ls -al