name: ielts-ai ci
on:
  push:
    branches:
      - main

jobs:
  my-job:
    name: generate output
    runs-on: ubuntu-latest
    # container: docker.io/centos:8
    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install env
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - name: test gcc
      run: |
        echo $(gcc -v)
  
    - name: bazel build
      run: |
        bazel build //...
